//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package br.com.felipejade.annotationsexemplo;

import android.os.Bundle;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.TextView;
import br.com.felipejade.annotationsexemplo.R.layout;

public final class CervejaFragment_
    extends CervejaFragment
{

    private View contentView_;

    private void init_(Bundle savedInstanceState) {
    }

    @Override
    public void onCreate(Bundle savedInstanceState) {
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
    }

    private void afterSetContentView_() {
        nome = ((TextView) findViewById(br.com.felipejade.annotationsexemplo.R.id.cerveja_nome));
        fabricante = ((TextView) findViewById(br.com.felipejade.annotationsexemplo.R.id.cerveja_cervejaria));
        teorAlcoolico = ((TextView) findViewById(br.com.felipejade.annotationsexemplo.R.id.cerveja_teor));
        descricao = ((TextView) findViewById(br.com.felipejade.annotationsexemplo.R.id.cerveja_descricao));
        preencherCerveja();
    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        contentView_ = super.onCreateView(inflater, container, savedInstanceState);
        if (contentView_ == null) {
            contentView_ = inflater.inflate(layout.cerveja_frag, container, false);
        }
        return contentView_;
    }

    @Override
    public void onViewCreated(View view, Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);
        afterSetContentView_();
    }

    public View findViewById(int id) {
        if (contentView_ == null) {
            return null;
        }
        return contentView_.findViewById(id);
    }

    public static CervejaFragment_.FragmentBuilder_ builder() {
        return new CervejaFragment_.FragmentBuilder_();
    }

    public static class FragmentBuilder_ {

        private Bundle args_;

        private FragmentBuilder_() {
            args_ = new Bundle();
        }

        public CervejaFragment build() {
            CervejaFragment_ fragment_ = new CervejaFragment_();
            fragment_.setArguments(args_);
            return fragment_;
        }

    }

}
