//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package br.com.felipejade.annotationsexemplo;

import java.util.ArrayList;
import android.R.id;
import android.app.Activity;
import android.content.Context;
import android.content.Intent;
import android.os.Bundle;
import android.os.Handler;
import android.util.Log;
import android.view.View;
import android.view.ViewGroup.LayoutParams;
import android.widget.ListView;
import br.com.felipejade.annotationsexemplo.R.layout;
import br.com.felipejade.annotationsexemplo.models.Cerveja;
import com.googlecode.androidannotations.api.BackgroundExecutor;

public final class ListarCervejasActivity_
    extends ListarCervejasActivity
{

    private Handler handler_ = new Handler();

    @Override
    public void onCreate(Bundle savedInstanceState) {
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        setContentView(layout.lista_cervejas);
    }

    private void init_(Bundle savedInstanceState) {
    }

    private void afterSetContentView_() {
        listView = ((ListView) findViewById(id.list));
        init();
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        afterSetContentView_();
    }

    @Override
    public void setContentView(View view, LayoutParams params) {
        super.setContentView(view, params);
        afterSetContentView_();
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        afterSetContentView_();
    }

    public static ListarCervejasActivity_.IntentBuilder_ intent(Context context) {
        return new ListarCervejasActivity_.IntentBuilder_(context);
    }

    @Override
    public void listarCervejas(final ArrayList<Cerveja> cervejas) {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                try {
                    ListarCervejasActivity_.super.listarCervejas(cervejas);
                } catch (RuntimeException e) {
                    Log.e("ListarCervejasActivity_", "A runtime exception was thrown while executing code in a runnable", e);
                }
            }

        }
        );
    }

    @Override
    public void baixarCervejas() {
        BackgroundExecutor.execute(new Runnable() {


            @Override
            public void run() {
                try {
                    ListarCervejasActivity_.super.baixarCervejas();
                } catch (RuntimeException e) {
                    Log.e("ListarCervejasActivity_", "A runtime exception was thrown while executing code in a runnable", e);
                }
            }

        }
        );
    }

    public static class IntentBuilder_ {

        private Context context_;
        private final Intent intent_;

        public IntentBuilder_(Context context) {
            context_ = context;
            intent_ = new Intent(context, ListarCervejasActivity_.class);
        }

        public Intent get() {
            return intent_;
        }

        public ListarCervejasActivity_.IntentBuilder_ flags(int flags) {
            intent_.setFlags(flags);
            return this;
        }

        public void start() {
            context_.startActivity(intent_);
        }

        public void startForResult(int requestCode) {
            if (context_ instanceof Activity) {
                ((Activity) context_).startActivityForResult(intent_, requestCode);
            } else {
                context_.startActivity(intent_);
            }
        }

    }

}
